name: twemoji
description: Twitter Emojis for Flutter, this package supports svg and png 72x72 emojis
version: 0.4.1
homepage: https://github.com/bigblackclock/twemoji

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  io: ^1.0.3

  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/png/
    - assets/svg/

executables:
  include_emojis: